<?php
//Create In House Ad custom post type
if ( !function_exists( 'hAds_cpts' ) ) {
	function hAds_cpts() {

		/**
		 * Post Type: House Ads.
		 */

		$labels = array(
			"name" => __( "House Ads", "" ),
			"singular_name" => __( "House Ad", "" ),
			"menu_name" => __( "House Ads", "" ),
			"all_items" => __( "All Ads", "" ),
			"add_new" => __( "Create Ads Group", "" ),
			"add_new_item" => __( "Add new Ads Group", "" ),
			"edit_item" => __( "Edit Ads Group", "" ),
			"new_item" => __( "New Ads Group", "" ),
			"view_item" => __( "View Ads Group", "" ),
			"view_items" => __( "View Ads Groups", "" ),
			"search_items" => __( "Search Ads Group", "" ),
			"not_found" => __( "Ads Group not found", "" ),
		);

		$args = array(
			"label" => __( "House Ads", "" ),
			"labels" => $labels,
			"description" => "In-House Ads",
			"public" => false,
			"publicly_queryable" => true,
			"show_ui" => true,
			"delete_with_user" => false,
			"show_in_rest" => true,
			"rest_base" => "",
			"rest_controller_class" => "WP_REST_Posts_Controller",
			"has_archive" => false,
			"show_in_menu" => true,
			"show_in_nav_menus" => true,
			"exclude_from_search" => true,
			"capability_type" => "post",
			"map_meta_cap" => true,
			"hierarchical" => false,
			"rewrite" => array( "slug" => "house_ads", "with_front" => true ),
			"query_var" => true,
			"menu_icon" => "dashicons-megaphone",
			"supports" => array( "title"),
			"taxonomies" => array( "ads_keywords" ),
		);

		register_post_type( "house_ads", $args );
	}

	add_action( 'init', 'hAds_cpts' );
}

//Generate House Ad keywords
if ( !class_exists( 'hAds_keywords' ) ) {
	class hAds_keywords {

	    function __construct() {
	        register_activation_hook( __FILE__,array( $this,'activate' ) );
	        add_action( 'init', array( $this, 'create_cpts_and_taxonomies' ) );
	    } 

	    function activate() {
	        $this->create_cpts_and_taxonomies();
	    }

	    function create_cpts_and_taxonomies() {

			$args = array(
				"label" => __( "Keywords", "" ),
				"labels" => $labels,
				"public" => false,
				"publicly_queryable" => true,
				"hierarchical" => false,
				"show_ui" => true,
				"show_in_menu" => true,
				"show_in_nav_menus" => flase,
				"query_var" => true,
				"rewrite" => array( 'slug' => 'ads_keywords', 'with_front' => true, ),
				"show_admin_column" => false,
				"show_in_rest" => false,
				"rest_base" => "ads_keywords",
				"rest_controller_class" => "WP_REST_Terms_Controller",
				"show_in_quick_edit" => false,
				);
	      register_taxonomy( "ads_keywords", array( "house_ads" ), $args );
	    }
	}
	$hAds_keywords = new hAds_keywords();
}

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5bec73d7d48ba',
		'title' => 'House Ads',
		'fields' => array(
			array(
				'key' => 'field_5bec73df9ec04',
				'label' => 'Square Ad',
				'name' => 'square_ad',
				'type' => 'image',
				'instructions' => '250 x 250 – Square',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => 250,
				'min_height' => 250,
				'min_size' => '',
				'max_width' => 250,
				'max_height' => 250,
				'max_size' => 1,
				'mime_types' => 'jpg, gif, png',
			),
			array(
				'key' => 'field_5bec88951f2cd',
				'label' => 'Small Square',
				'name' => 'small_square',
				'type' => 'image',
				'instructions' => '200 x 200',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => 200,
				'min_height' => 200,
				'min_size' => '',
				'max_width' => 200,
				'max_height' => 200,
				'max_size' => 1,
				'mime_types' => 'jpg, gif, png',
			),
			array(
				'key' => 'field_5bec88b31f2ce',
				'label' => 'Banner',
				'name' => 'banner',
				'type' => 'image',
				'instructions' => '468 x 60 – Banner',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => 468,
				'min_height' => 60,
				'min_size' => '',
				'max_width' => 468,
				'max_height' => 60,
				'max_size' => 1,
				'mime_types' => 'jpg, gif, png',
			),
			array(
				'key' => 'field_5bec88cf1f2cf',
				'label' => 'Leaderboard',
				'name' => 'leaderboard',
				'type' => 'image',
				'instructions' => '728 x 90 – Leaderboard',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => 728,
				'min_height' => 90,
				'min_size' => '',
				'max_width' => 728,
				'max_height' => 90,
				'max_size' => 1,
				'mime_types' => 'jpg, gif, png',
			),
			array(
				'key' => 'field_5bec88fd1f2d0',
				'label' => 'Inline Rectangle',
				'name' => 'inline_rectangle',
				'type' => 'image',
				'instructions' => '300 x 250 – Inline Rectangle',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => 300,
				'min_height' => 250,
				'min_size' => '',
				'max_width' => 300,
				'max_height' => 250,
				'max_size' => 1,
				'mime_types' => 'jpg, gif, png',
			),
			array(
				'key' => 'field_5bec89311f2d2',
				'label' => 'Large Rectangle',
				'name' => 'large_rectangle',
				'type' => 'image',
				'instructions' => '336 x 280 – Large Rectangle',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => 336,
				'min_height' => 280,
				'min_size' => '',
				'max_width' => 336,
				'max_height' => 280,
				'max_size' => 1,
				'mime_types' => 'jpg, gif, png',
			),
			array(
				'key' => 'field_5bec89481f2d3',
				'label' => 'Skyscraper',
				'name' => 'skyscraper',
				'type' => 'image',
				'instructions' => '120 x 600 – Skyscraper',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => 120,
				'min_height' => 600,
				'min_size' => '',
				'max_width' => 120,
				'max_height' => 600,
				'max_size' => 1,
				'mime_types' => 'jpg, gif, png',
			),
			array(
				'key' => 'field_5bec895c1f2d4',
				'label' => 'Wide Skyscraper',
				'name' => 'wide_skyscraper',
				'type' => 'image',
				'instructions' => '160 x 600 – Wide Skyscraper',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => 160,
				'min_height' => 600,
				'min_size' => '',
				'max_width' => 160,
				'max_height' => 600,
				'max_size' => 1,
				'mime_types' => 'jpg, gif, png',
			),
			array(
				'key' => 'field_5bec89721f2d5',
				'label' => 'Half-Page Ad',
				'name' => 'half-page',
				'type' => 'image',
				'instructions' => '300 x 600 – Half-Page Ad',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => 160,
				'min_height' => 600,
				'min_size' => '',
				'max_width' => 160,
				'max_height' => 600,
				'max_size' => 1,
				'mime_types' => 'jpg, gif, png',
			),
			array(
				'key' => 'field_5bec89861f2d6',
				'label' => 'Large Leaderboard',
				'name' => 'large_leaderboard',
				'type' => 'image',
				'instructions' => '970 x 90 – Large Leaderboard',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => 160,
				'min_height' => 600,
				'min_size' => '',
				'max_width' => 160,
				'max_height' => 600,
				'max_size' => 1,
				'mime_types' => 'jpg, gif, png',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'house_ads',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5bfc1c21159c1',
		'title' => 'Shortcode Generator',
		'fields' => array(
			array(
				'key' => 'field_5bfc1c549b2e2',
				'label' => 'Ad size',
				'name' => 'ad_size',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => 'adSize',
				),
				'choices' => array(
					'square_ad' => 'Square Ad',
					'small_square' => 'Small Square',
					'banner' => 'Banner',
					'leaderboard' => 'Leaderboard',
					'inline_rectangle' => 'Inline Rectangle',
					'large_rectangle' => 'Large Rectangle',
					'skyscraper' => 'Skyscrapper',
					'wide_skyscraper' => 'Wide Skyscraper',
					'half-page' => 'Half-Page Ad',
					'large_leaderboard' => 'Large Leaderboard',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5bfc1d1d9b2e4',
				'label' => 'Ad URL',
				'name' => 'ad_url',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => 'adURL',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5bfc1d249b2e5',
				'label' => 'Link Options',
				'name' => 'link_options',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => 'LinkOptions',
				),
				'choices' => array(
					'_blank' => 'Open in a new window',
					'nofollow' => 'Don\'t follow link on this page',
				),
				'allow_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'value',
				'save_custom' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'house_ads',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
endif;